--Define context
USE ROLE DB_ENGINEER;
USE WAREHOUSE LOAD_WH;
USE DATABASE FPL_ONTOLOGY_DB;
USE SCHEMA FPL_STAGING;

--Truncate and load RAW_FIXTURES table (CSV file format)
TRUNCATE TABLE RAW_FIXTURES;
COPY INTO RAW_FIXTURES FROM @FPL_DATA_STAGE/fixtures.csv
    FILE_FORMAT=(FORMAT_NAME=FPL_CSV_FORMAT) 
    ON_ERROR='ABORT_STATEMENT';

--Truncate and load RAW_GAMEWEEKS table (CSV file format)
TRUNCATE TABLE RAW_GAMEWEEKS;
COPY INTO RAW_GAMEWEEKS FROM @FPL_DATA_STAGE/gameweeks.csv
    FILE_FORMAT=(FORMAT_NAME=FPL_CSV_FORMAT) 
    ON_ERROR='ABORT_STATEMENT';

--Truncate and load RAW_GW_STATS table (JSON file format)
TRUNCATE TABLE RAW_GW_STATS;
COPY INTO RAW_GW_STATS (PLAYER_ID, GAMEWEEK_ID, FIXTURE_ID, STATS) 
FROM 
(
SELECT 
    $1:PLAYER_ID::INTEGER, 
    $1:GAMEWEEK_ID::INTEGER, 
    $1:FIXTURE_ID::INTEGER,
    $1:STATS
FROM @FPL_DATA_STAGE/gw_stats.json
)
    FILE_FORMAT=(FORMAT_NAME=FPL_JSON_FORMAT) 
    ON_ERROR='ABORT_STATEMENT';

--Truncate and load RAW_PLAYERS table (CSV file format)
TRUNCATE TABLE RAW_PLAYERS;
COPY INTO RAW_PLAYERS FROM @FPL_DATA_STAGE/players.csv
    FILE_FORMAT=(FORMAT_NAME=FPL_CSV_FORMAT) 
    ON_ERROR='ABORT_STATEMENT';

--Truncate and load RAW_POSITIONS table (CSV file format)
TRUNCATE TABLE RAW_POSITIONS;
COPY INTO RAW_POSITIONS FROM @FPL_DATA_STAGE/positions.csv
    FILE_FORMAT=(FORMAT_NAME=FPL_CSV_FORMAT) 
    ON_ERROR='ABORT_STATEMENT';

--Truncate and load RAW_TEAMS table (CSV file format)
TRUNCATE TABLE RAW_TEAMS;
COPY INTO RAW_TEAMS FROM @FPL_DATA_STAGE/teams.csv
    FILE_FORMAT=(FORMAT_NAME=FPL_CSV_FORMAT) 
    ON_ERROR='ABORT_STATEMENT';
