--Define context
USE ROLE DB_ENGINEER;
USE WAREHOUSE LOAD_WH;
USE DATABASE FPL_ONTOLOGY_DB;
USE SCHEMA FPL_PRESENTATION;

/*
================================================================================================================
1. Create flattened views from each node in KG_NODE
================================================================================================================
*/


CREATE OR REPLACE VIEW V_TEAM AS
SELECT
    NODE_ID,
    NAME AS TEAM_NAME,
    PROPS:team_id::INT AS TEAM_ID,
    PROPS:strength::INT AS STRENGTH,
    PROPS:strength_overall_home::INT AS STRENGTH_OVERALL_HOME,
    PROPS:strength_overall_away::INT AS STRENGTH_OVERALL_AWAY,
    PROPS:strength_attack_home::INT AS STRENGTH_ATTACK_HOME,
    PROPS:strength_attack_away::INT AS STRENGTH_ATTACK_AWAY,
    PROPS:strength_defence_home::INT AS STRENGTH_DEFENCE_HOME,
    PROPS:strength_defence_away::INT AS STRENGTH_DEFENCE_AWAY
FROM FPL_KG.KG_NODE
WHERE NODE_TYPE = 'TEAM';
 
CREATE OR REPLACE VIEW V_POSITION AS
SELECT
    NODE_ID,
    NAME AS POSITION_NAME,
    PROPS:position_id::INT AS POSITION_ID,
    PROPS:short_name::VARCHAR(3) AS SHORT_NAME,
    PROPS:num_players::INT AS NUM_PLAYERS
FROM FPL_KG.KG_NODE
WHERE NODE_TYPE = 'POSITION';
 
CREATE OR REPLACE VIEW V_PLAYER AS
SELECT
    NODE_ID,
    NAME AS PLAYER_NAME,
    PROPS:player_id::INTEGER AS PLAYER_ID,
    PROPS:first_name::VARCHAR(50) AS FIRST_NAME,
    PROPS:second_name::VARCHAR(50) AS SECOND_NAME,
    PROPS:birth_date::DATE AS BIRTH_DATE,
    PROPS:selected_by_percent::NUMBER(10,2) AS SELECTED_BY_PERCENT
FROM FPL_KG.KG_NODE
WHERE NODE_TYPE = 'PLAYER';
 
CREATE OR REPLACE VIEW V_GAMEWEEK AS
SELECT
    NODE_ID,
    NAME AS GAMEWEEK_NAME,
    PROPS:gameweek_id::INT AS GAMEWEEK_ID,
    PROPS:deadline_time::TIMESTAMP_NTZ AS DEADLINE_TIME,
    PROPS:average_entry_score::INT AS AVERAGE_ENTRY_SCORE,
    PROPS:highest_score::INT AS HIGHEST_SCORE,
    PROPS:transfers_made::INT AS TRANSFERS_MADE
FROM FPL_KG.KG_NODE
WHERE NODE_TYPE = 'GAMEWEEK';
 
CREATE OR REPLACE VIEW V_FIXTURE AS
SELECT
    NODE_ID,
    PROPS:fixture_id::INT AS FIXTURE_ID,
    PROPS:kickoff_time::TIMESTAMP_NTZ AS KICKOFF_TIME,
    PROPS:team_h_score::INT AS TEAM_H_SCORE,
    PROPS:team_a_score::INT AS TEAM_A_SCORE
FROM FPL_KG.KG_NODE
WHERE NODE_TYPE = 'FIXTURE';
 

CREATE OR REPLACE VIEW V_PERFORMANCE AS
SELECT
    NODE_ID,
    PROPS:starts::INT = 1 AS STARTED,
    PROPS:minutes::INT AS MINUTES,
    PROPS:goals_scored::INT AS GOALS_SCORED,
    PROPS:assists::INT AS ASSISTS,
    PROPS:clean_sheets::INT AS CLEAN_SHEETS,
    PROPS:goals_conceded::INT AS GOALS_CONCEDED,
    PROPS:own_goals::INT AS OWN_GOALS,
    PROPS:penalties_saved::INT AS PENALTIES_SAVED,
    PROPS:penalties_missed::INT AS PENALTIES_MISSED,
    PROPS:yellow_cards::INT AS YELLOW_CARDS,
    PROPS:red_cards::INT AS RED_CARDS,
    PROPS:saves::INT AS SAVES,
    PROPS:bonus::INT AS BONUS,
    PROPS:bps::INT AS BPS,
    PROPS:influence::NUMBER(10,2) AS INFLUENCE,
    PROPS:creativity::NUMBER(10,2) AS CREATIVITY,
    PROPS:threat::NUMBER(10,2) AS THREAT,
    PROPS:ict_index::NUMBER(10,2) AS ICT_INDEX,
    PROPS:points::INT AS POINTS,
    PROPS:defensive_contribution::INT AS DEFENSIVE_CONTRIBUTION,
    PROPS:expected_goals::NUMBER(10,2) AS EXPECTED_GOALS,
    PROPS:expected_assists::NUMBER(10,2) AS EXPECTED_ASSISTS,
    PROPS:expected_goal_involvements::NUMBER(10,2) AS EXPECTED_GOAL_INVOLVEMENTS,
    PROPS:expected_goals_conceded::NUMBER(10,2) AS EXPECTED_GOALS_CONCEDED,
    PROPS AS ALL_STATS
FROM FPL_KG.KG_NODE
WHERE NODE_TYPE = 'PERFORMANCE';
